# Generated by Django 5.1.7 on 2025-04-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalFloors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('floor_img', models.ImageField(blank=True, null=True, upload_to='floorimg/')),
            ],
        ),
    ]
