# Generated by Django 5.1.7 on 2025-04-10 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textiles', '0002_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('fabric', models.CharField(max_length=100)),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='productimg')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textiles.totalfloors')),
            ],
        ),
    ]
