# Generated by Django 5.1.7 on 2025-04-11 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textiles', '0003_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totalfloors', to='textiles.totalfloors'),
        ),
    ]
